create table respuestas(
	id serial primary key,
    nombre varchar(50),
	p1 int,
    tiempo1 numeric,
	p2 int,
    tiempo2 numeric,
	p3 int,
    tiempo3 numeric,
	p4 int,
    tiempo4 numeric,
	p5 int,
    tiempo5 numeric,
	p6 int,
    tiempo6 numeric,
	p7 int,
    tiempo7 numeric,
	p8 int,
    tiempo8 numeric,
	p9 int,
    tiempo9 numeric,
	p10 int,
    tiempo10 numeric,
	p11 int,
    tiempo11 numeric,
	p12 int,
    tiempo12 numeric,
	p13 int,
    tiempo13 numeric,
	p14 int,
    tiempo14 numeric,
	p15 int,
    tiempo15 numeric
)